### ISSUE TITLE
Add scheduler module

### ISSUE THREAD

**Issue by dcdolson** [dcdolson/nsh-sf-devkit#3]
Instead of having applications implement the while(1) loop, move to a library.

**Comment by klarose** [comment]
I've implemented a rudimentary version of this in the Scheduler library.

Right now is assumes a single interface, and either uses poll or just sleeps a fixed period of time before calling run.

**Comment by dcdolson** [comment]
We could consider using boost::asio for the scheduler.

From: klarose
Sent: Sunday, November 6, 2016 9:30 AM
To: dcdolson/nsh-sf-devkit
Reply To: dcdolson/nsh-sf-devkit
Cc: Dave Dolson; Author
Subject: Re: [dcdolson/nsh-sf-devkit] Add scheduler module (#3)

I've implemented a rudimentary version of this in the Scheduler library.

Right now is assumes a single interface, and either uses poll or just sleeps a fixed period of time before calling run.
